### ISSUE TITLE
UART --> I2C

### ISSUE THREAD

**Issue by gracelower** [COAST-Lab/c3po#29]
Have spent much time attempting to switch EZO RTD circuit from UART to I2C mode based on the documentation provided, but:
- RTD will only blink cyan/green (UART mode); pictured below
https://www.whiteboxes.ch/docs/tentacle/t2-mkII/#/protocols

![IMG_3808](https://github.com/user-attachments/assets/af610d16-e4a2-4060-a18b-78ba27a12191)

Was able to get EZO EC circuit to blink dark blue (I2C) after many attempts; pictured below.

![IMG_3810](https://github.com/user-attachments/assets/e1d1f688-7baf-446e-a0ab-4d6ff9d537ec)

**Comment by SUPScientist** [comment]
I don't think this will fix your problem with the Atlas EZO circuit, but to at least eliminate one variable, I recommend flashing a blink LED script to your Boron with cell disabled. E.g., this one: https://github.com/SUPScientist/Smart-Coasts/blob/main/Class-01-Intro/Blink_LED.cpp. This might resolve the issue @efarq was describing re: Particle wanting you to claim the Boron, which I don't think should be necessary yet as long as you use `SYSTEM_MODE(SEMI_AUTOMATIC);`.

**Comment by SUPScientist** [comment]
Next, could you confirm which documentation you are following to put the device into I2C mode? Is it https://files.atlas-scientific.com/EZO_RTD_Datasheet.pdf?

**Comment by gracelower** [comment]
> Next, could you confirm which documentation you are following to put the device into I2C mode? Is it https://files.atlas-scientific.com/EZO_RTD_Datasheet.pdf?

Yes, that is the protocol I have been using, also described here: https://www.whiteboxes.ch/docs/tentacle/t2-mkII/#/protocols

I just worked through these steps again and seem to still only receive cyan/green blinking on the RTD. The EC switched to I2C properly (dark blue).

**Comment by SUPScientist** [comment]
My questions are probably unhelpful because I know you're really thorough, but since I can't exactly see what pins you have connected to which, can you confirm that this is exactly what you're doing:
<img width="990" alt="image" src="https://github.com/user-attachments/assets/e105b255-5239-4714-940b-498370f22f06">

Idea 2: use the Boron's 3V3 as your power to the VCC port on the EZO board.

Idea 3: if that still doesn't work, you could also try to send a command via UART (hook up the Boron's 3V3 and GND to the RTD EZO's VCC and GND and then the Boron's Rx to the EZO's Tx and vice versa). Then put a line in your `void loop()` function that is, I think, `Serial1.println('I2C,100');` Note that it will then use 100 as the address if it works. You also have to reboot it (disconnect/reconnect power to EZO) to see if new color appears to indicate I2C mode.

**Comment by gracelower** [comment]
Update:
Was able to get RTD to cyan/aqua blinking --> indicates I2C communication
EC is still showing solid blue --> indicates UART connection
When powering from Boron's 3V3 instead of VUSB, I am able to get a solid green, which I think indicates standby mode, though does not indicate whether it's in I2C or UART.
Will try Idea 3 soon! Thanks for the assistance!

**Comment by gracelower** [comment]
![image](https://github.com/user-attachments/assets/8e2e048e-64a2-4577-980d-809d8423f5f4)
![IMG_4160](https://github.com/user-attachments/assets/2ac22710-43d9-49c7-8178-6b57e440a734)
![IMG_4161](https://github.com/user-attachments/assets/ab1b4219-ee8e-4115-8493-ba6038cf544d)

**Comment by gracelower** [comment]
@efarq Tagging you in this issue for your question about changing the EC EZO board from UART to I2C. I'm wondering if there may be some helpful hints documented here.

The instructions I wrote last year for converting from UART to I2C can be found here: https://github.com/COAST-Lab/c3po/tree/main/Documentation I think you have already tried these steps but linking just in case.
