### ISSUE TITLE
Test code w/ sensors

### ISSUE THREAD

**Issue by gracelower** [COAST-Lab/c3po#32]
Code ([Firmware/AtlasConductivity_20240724](https://github.com/COAST-Lab/c3po/tree/ce125387664c0b1ae50e006cd57f2a87b746afdf/Firmware/AtlasConductivity_20240724)) compiles and flashes properly when using Boron 6.1.1 device & OS. However, when opening the serial monitor, it is blank (i.e. `Serial monitor opened successfully` and nothing else).

I have tried:
- following the set-up instructions as written here: https://github.com/gracelower/c3po/blob/main/Documentation/SetUp.md
- following this pinout: https://files.atlas-scientific.com/i3-interlink-datasheet.pdf (page 5)
- changing `SECONDS_BETWEEN_MEASUREMENTS = 360` to `60` for testing

**Comment by gracelower** [comment]
Tried with only EZO EC circuit, Atlas Isolated Carrier Board, EZO EC probe, and Boron / Adalogger.
Wired VCC / 3V3, GND / GND, SDA / SDA, SCL / SCL.
Still receiving blank serial monitor.

EZO EC is correctly showing dark blue LED which is I2C.
Boron blinks green, which on Particle website, is indicated as "connecting to network." Could this be a source of error? I would think the device would still be recording internally on the microSD card even if no network connection exists, though Dr. Hino said we do not have a microSD card in Chapel Hill, so I haven't been able to check if it has been storing data.

**Comment by SUPScientist** [comment]
Yes, blinking green is the problem (or at least one of them). This step of connecting to the network is considered "blocking"; that is, it won't go to the next step until it resolves that one (so, no, it won't record to micro-SD). It can't resolve that connecting step without being claimed (not sure if it has been— @efarq?). 

Try going back to `PUBLISHING 0` in 
https://github.com/COAST-Lab/c3po/blob/ce125387664c0b1ae50e006cd57f2a87b746afdf/Firmware/AtlasConductivity_20240724/src/AtlasConductivity_20240724.cpp#L44

This will allow the firmware to skip trying to connect. The Boron should then breathe white, not flash green (please confirm).

Also, if you do stop by the lab this week, make sure you collect a micro-SD card reader so that we can solve that problem!

**Comment by gracelower** [comment]
The Boron has been claimed via the Particle app (special thanks to @efarq for help with that!)
I will go back to `PUBLISHING 0` now and see if that makes any adjustments to the LED status!

**Comment by gracelower** [comment]
Updates:
- I have tried `PUBLISHING 0` and unfortunately am only getting the device to blink green; I will read Particle forum posts to see if anyone in the "Particle-verse" has experienced this issue 
- Maybe I can manually turn off the network connection through the Particle Console / app?
- Found a converter at my house; no files on microSD card (expected, since sensor is being blocked)

**Comment by SUPScientist** [comment]
Have you gone through the getting started steps that you used (and for that matter helped write!) for the open-water-level sensor (https://github.com/COAST-Lab/Open-Water-Level/blob/main/Firmware/Getting_Started%20with%20Cell-Enabled%20Water%20Level%20Sensing.md)? For instance, have you confirmed that the Boron is running the same Device OS that you are compiling for (it looks from the following to be 6.1.1):
https://github.com/COAST-Lab/c3po/blob/ce125387664c0b1ae50e006cd57f2a87b746afdf/Firmware/AtlasConductivity_20240724/.vscode/settings.json#L8

My next advice would be to take a giant step back and confirm that you can get the Boron to do anything that you want it to do, such as blink an LED. If you can strip away any unnecessary complexity to see what is and isn't working and then build it back up, that will help identify the source of the problem(s).

**Comment by SUPScientist** [comment]
As we've learned more here, it is clear that the limiting factor is with controlling the Boron itself rather than a sensor issue. Let's move Boron troubleshooting over to a new issue here (https://github.com/COAST-Lab/c3po/issues/34) and come back to this issue when it is time to test the sensors again (i.e., once we can make the Boron do what we want it to do!).

**Comment by gracelower** [comment]
In reference to: https://github.com/COAST-Lab/c3po/issues/34#issuecomment-2555770926

<img width="725" alt="Image" src="https://github.com/user-attachments/assets/24654d1a-4f9c-4ebe-b472-a99526208c87" />

**Comment by gracelower** [comment]
Pictured is an example of output after ...
- wiring Boron / Adalogger to Port 4 on Tentacle T3 Shield instead of upper rows of pins
- reformatting microSD card from exFAT to FAT32 for compatibility with the Adalogger
- adding delays to code to account for sleep timing & serial connections

<img width="429" alt="Image" src="https://github.com/user-attachments/assets/0f7d4fd9-f062-44c4-8824-5c2da80eabff" />
